version: "3.8"
services:
    socialapi:
        image: socialapi:1.0
        ports:
            - "3500:3500"
        networks:
            - interna_mreza
    authapi:
        image: authapi:1.0
        ports:
            - "9000:9000"
        networks:
            - interna_mreza
networks:
    interna_mreza:
        driver: bridge
